name: Deploy to EC2 via SSM Run Command

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: mkzip
        run: |
          zip -r app.zip . -x "*.git*" -x "*.github/*"


        with:
          document-name: "AWS-RunShellScript"
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          parameters: |
            commands=[
              "cd /home/ubuntu/app",
              "git pull origin main",
              "bash mkdeploy.sh"
            ]
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}